version: '3'

services:
  dhcp:
    build:
      context: ./dhcp
    container_name: dhcp_container
    ports:
      - "67:67/udp"
    networks:
      - internal_network
    volumes:
      - ./dhcp/dhcpd.conf:/etc/dhcp/dhcpd.conf

  dns:
    build:
      context: ./dns
    container_name: dns_container
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      - internal_network
    volumes:
      - ./dns/named.conf.options:/etc/bind/named.conf.options

  firewall:
    build:
      context: ./firewall
    container_name: firewall_container
    network_mode: "host"
    volumes:
      - ./firewall/firewall.sh:/root/firewall.sh

networks:
  internal_network:
    driver: bridge
